name: example_drift_with_bloc
description: "Example flutter project using drift with bloc"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  repo:
    path: ./packages/repo
  drift:
  drift_flutter:
  bloc:
  get_it:
  cupertino_icons:

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev:
  build_runner:
  flutter_lints:

flutter:
  uses-material-design: true
